language: node_js
before_script:
- npm install
- npm run build
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: o9kcPUmzRTqrZdxUhONWZ16C+2giLRrbhrIqZ0F6k/wP2SaOboY05XbtAVtJ1VtH+AYmXtyQlMvUvZyYSP8dAbG6APbu+VXCb1p69pOlevP5CQ/3B4J8aTGiKL/O5mJ1nDVVpRJkzIZVB+xTCBLGq1qDIkJaCCfRYiN0fuXwVidCOegMPs7tGqQoRNzhnoNWfjqlgJBPdt4pzs57TwNtT7CtdJ9lVSmfoWcdySsmiCwc949eTg5h1zoDApPUsbcJvEM1qHff9SyWoBze7yW/4bKy5phyJ2AY0M+7ysX+faLqUiF4kRkkjjp6JWZBiuPt6qepRWwvqo9FB3AkQg5D5BNXH2bQtYlZclYm6onmh+7eW0pf+yTAu/UlZBMHXvbghIbMkfSP01bQGSW+S3zyJ7CVhyvrBWlFXOes+l07JBUU6jMPAZKJW8M9k2lrWkkJlBGUbWNbJ/ULkTxIBc7RjqStw0k7mVawT+6gp1sG/ZIDVUkBLI2/svDYBfGoIbwJBoShjCakjAOh+ngB1Mq2XRIJAmFnmfQk+2/KkBaNtN5fsGjbFEMnMJPbRMC0BVlYLmEvh1itKiEuSghhnUGAOBmP0J+etM2te63/C/DwuO73wD0L/bjzFtt6LAOYWPSeiXSyZNMMkSNE5BmBSMfZLmvAH1Qo7ZG+QzWzX4kvZQs=
  app: foodwise-api
  on:
    repo: sejinkim1904/foodwise_api
